version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cellphone-app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped

  mysql-db:
    image: mysql:5.7
    container_name: cellphone-db
    volumes:
      - db-store:/var/lib/mysql
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment: 
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: "Asia/Ho_Chi_Minh"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+07:00']  

volumes:
  db-store:
    driver: local
